### ISSUE TITLE
Feature request: Keep the oldest/newest file

### ISSUE THREAD

**Issue by nuriakman** [adrianlopezroche/fdupes#113]
Need option for deleting files:
Keep old file (by file creation time) and delete others
Keep new file (by file creation time) and delete others

This parameter may be shortcut for ORDER and/or REVERSE ORDER parameters.

**Comment by adrianlopezroche** [comment]
I'm trying not to add too many command-line options. If --delete and
--noprompt along with the proper choice of order will produce the desired
effect, then there's really no reason to add yet another option.

BTW, there's no such thing as file creation time in Unix. There's
modification time, change time, and access time, but no creation time.

**Comment by vedia** [comment]
Modification time also possible. You know, duplicate files mostly created by copy and paste. Also files have copied from mobile phones or USB drives more than once.

**Comment by adrianlopezroche** [comment]
fdupes --delete --noprompt --order=time [directory] to keep oldest files.

Add --reverse to keep newest files instead.

**Comment by moonshiner** [comment]
Just this week I was cursing and thinking fdupes should have some of that --exclude type logic rsync/diff uses.  But barring that, when -1 is selected, I would like to select the separator value instead of ' '.  I had a bunch of dupes that were in a mixed order and I ended up dumping all the names with -1 and then doing a bunch of chicanery to split the lines into two fields since many files had spaces already.   maybe "-1 <separator> --sameline=<separator>"  where the default is " " ?
