### ISSUE TITLE
--recursive: option is broken

### ISSUE THREAD

**Issue by adrianlopezroche** [adrianlopezroche/fdupes#123]
$ fdupes --recursive: testdir
output:
fdupes: -R option must be isolated from other options

$ fdupes --recurse: testdir
works as expected

**Comment by jbruchon** [comment]
Looks like `--recurse:` is hard-coded and that's why the other option doesn't work: https://github.com/adrianlopezroche/fdupes/blob/master/fdupes.c#L1326

@adrianlopezroche Might be better to just remove the availability `--recursive` options entirely. They aren't in the help text and are redundant. It would be a faster and less bloated fix. What do you think?

**Comment by adrianlopezroche** [comment]
Good point. Fixed by 85c5f9e1727646d7b43fa6f2a4136fb9c86d29f6.
