### ISSUE TITLE
Order by filesize for use with -dN flags

### ISSUE THREAD

**Issue by pluja** [adrianlopezroche/fdupes#149]
When deleting files with the `norpompt` option, one could be losing the 'better quality files'. From noprompt definition:
> together with --delete, preserve the **first** file in each set of duplicates and delete the rest without prompting the user

And from `orderby`:
> select sort order for output and deleting; by file modification time (BY='time'; default), status change time (BY='ctime'), or filename (BY='name')

One could use the `orderby` option to order by filesize so fdupes always preserves the biggest file (the one with more quality).

**Comment by jbruchon** [comment]
Only files of identical size can be duplicates. The program isn't content-aware. All files in a group are sorted by size already because all files in each duplicate group are the exact same size. In fact, one of the biggest speed boosts in the software is a size comparison before reading any actual files.

**Comment by pluja** [comment]
Okay! Nice!
