### ISSUE TITLE
Exit codes [feature request]

### ISSUE THREAD

**Issue by NicoWeio** [adrianlopezroche/fdupes#161]
A command like `fdupes x y` prints
```shell
fdupes: could not chdir to x
fdupes: could not chdir to y
```
to _stderr_ if the directories _x_ and _y_ do not exist, but the process has the exit code 0, despite obviously failing.
This caused me quite a headache today, because it just _assumed_ that fdupes would give another exit code in such a case.

I don't see anything about exit codes in this GitHub repo nor the man page, so I assume that there are none at the moment.
How exactly the error codes should be defined is a question I'm not qualified to answer, but I sure hope they will be added in the future. Thank you!

**Comment by adrianlopezroche** [comment]
The problem is that failure to chdir into a directory isn't generally a
fatal error. It can happen at any time during program execution such as
during filesystem traversal any number of directories deep (via --recurse)
or after having successfully processed the first n directories listed as
command line arguments but failing on argument n+1.

Given all this I choose to treat failure to chdir as a warning instead of
an error.

**Comment by NicoWeio** [comment]
I agree, that's understandable. Nonetheless, one might consider…
- A flag to change this behavior
- The special case where _none_ of the given directories could be processed. Then, at least, I'd consider the run failed. (But giving a non-zero exit code only in that case might feel inconsistent as well…)
