### ISSUE TITLE
Finding duplicate files including files in archives

### ISSUE THREAD

**Issue by Mathias-U1F596** [adrianlopezroche/fdupes#189]
Archives files shall be treated (not only as files, but also) as folders and scans for duplicates to find duplicate files in archives as well.

**Comment by jbruchon** [comment]
This would require pulling in an external dependency that can decompress several compressed formats, but also some pretty heavy changes in logic since it's a lot less practical to modify or delete the file within the archive. Repacking archives requires shifting all data after the deletion at a minimum and completely rebuilding the entire archive at worst. It would be a nice feature, but it is a technically challenging one to add. Decompression time and indicating progress so the user doesn't think the program has locked up could also become an issue.
