### ISSUE TITLE
Feature : save a md5sum/tree file for future compare

### ISSUE THREAD

**Issue by Georges760** [adrianlopezroche/fdupes#19]
It would be good to save the hash/parse/analyze information of a specific fdupes run, in order to compare later this "virtual"files tree with a real file tree.

For example, I have a huge photo database, I can run a long fdupes analyze and store the informations in a file. Then if later in my old HDD I found some photos, i could just run fdupes on these photo with an import of the "virtual" huge database to compare from...

**Comment by jbruchon** [comment]
The only problem is that fdupes scans full files to be absolutely certain that no md5 collisions will destroy unique files. Security hashes were intended to detect tampering, not to verify that all files in a directory tree are unique. The risk of collisions with modifications to the same file is low, but that risk skyrockets when dealing with lots of files of varying content and length. It would be a bit dangerous to rely solely on the hashing mechanisms to tag duplicates.
-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by AnrDaemon** [comment]
I don't see a problem.
Let's take current task I'm facing as example.
I have 12-13 years worth of company's rather chaotic development to sort through, kill dupes and otherwise optimize storage.
For each given file, there's usually a whole directory of dupes that I go to, check, compare and kill at once. After that, the whole list of files in the fdupes' log become irrelevant.
From this point, I have two choices.

1. Run fdupes again to sift through the same 120-something gigabytes of files, or
2. Try to filter out the files I just deleted from the log.

The first choice is, of course, preferred. But it takes hell of a lot of time to complete. It would be most convenient if it would (optionally) be able to save the hashes for future reference, or consume the md5sum output for the same purpose.

**Comment by jbruchon** [comment]
Being able to store hashes for future use is a feature I've been working on for a couple of months now; having the full file hashes pre-computed would be insanely helpful with large files and data sets. It would be wonderful to be able to scan 800,000 files with small, infrequent additions to the data set for duplicates WITHOUT scanning every file that was checked once before.

Unfortunately, this feature addition can't be quite as simple as "save a list of hashes and load them again for the next session." File metadata must be saved and loaded to ensure that stale hashes aren't used and all of this data storage requires either a data file format (preferably textual) specific to fdupes or linking in something like SQLite to store that data (with all the problems, bloat, and dependencies that an external DB engine adds.) There's also the problem of where and how to store the DB: in the directory where fdupes was run? In the user's home directory? Require an explicit command line specification for the file path? Should the DB be created and used by default or should the user explicitly request it? In the case of small amounts of small files, a database will only slow things down, and a one-shot run creating a list of hashes that never gets used is pointless.

**Comment by AnrDaemon** [comment]
I think you're overcomplicating it.
Yes, a full-featured, fool-proof solution would require preservation of file size at least, as hash, but think it through.
You will scan the suspected file to ensure bitvise duplication anyway. You could as well recalculate the hash at the same time. If hash wouldn't match the one stored in the provided list, you have all the rights to bark at the user to refresh the list first. It is up to the user's discretion, how to interpret the message and what action to take, if any.
For me? It would ever happen. 99% of the files are photos, which are so highly unlikely to change that I'm only re-comparing before deletion due to my progressive paranoia.

**Comment by adrianlopezroche** [comment]
Implemented in ab5ef95e2b2633d0ca1a5ae0b8ac41abde160100. Closing after 9 years. Sorry for the delay 😂.
