### ISSUE TITLE
ctime,atime sort order

### ISSUE THREAD

**Issue by rudepython** [adrianlopezroche/fdupes#60]
add ctime,atime to sort order options

**Comment by adrianlopezroche** [comment]
I've added an option to sort by ctime (https://github.com/adrianlopezroche/fdupes/commit/e95ec42dc178eff0410880c3dc4c0dac3df442df), but I don't think I'll be adding an option to sort by atime. The problem is that fdupes itself will cause atime values to change, which in my opinion rather defeats the purpose of sorting duplicates by atime (generally, "pick the file used least/most recently").
