### ISSUE TITLE
Please release version 2.x to remedy the current non-linear versioning mess

### ISSUE THREAD

**Issue by peti** [adrianlopezroche/fdupes#74]
We are having a hard time updating openSUSE to `fdupes-1.6.1`, because rpm won't consider the new package as an update to the version 1.51 that we already have. This is really unpleasant. We can add hacks to the spec file that work around this issue, i.e. by declaring

    Provides:       %{name} = 1.51.%{version}
    Obsoletes:      %{name} < 1.51.%{version}

..., but this is bad from a user's perspective because now our package manager will install the new version 1.6.1, but declare it a *downgrade*, which no doubt will result in tickets being opened, questions being posted to mainling lists, etc. From a distributors point of view, the breaking change between version 1.51 and 1.6.0 was really nasty and it's causing us (and our users) extra work and confusion.

Anyhow, there is an easy way out of this mess, and this is to release a new version that comes with a *higher* version number than 1.51. That could be 1.60.0, or it could be 2.0, which feels more reasonable I suppose.

@adrianlopezroche, would you mind going along with this proposal to help us (and others) distribute the latest version of your work properly?

**Comment by hasufell** [comment]
No action here?

**Comment by jbruchon** [comment]
Sadly, as far as I can see Adrian is not working on `fdupes` anymore. The last activity on any branches here is from October 2016 and the last contribution shown on Adrian's public activity graph here is from April 2017, about ten months ago. [I forked fdupes into jdupes some time ago](https://github.com/jbruchon/jdupes) and I try to tell people posting here about it since I have been more or less actively maintaining and updating it. I don't like to feel like I'm hijacking Adrian's project on his own turf but it's really the only way I can help out people showing up here looking for assistance since I have no control over `fdupes` and Adrian rejected my (admittedly fast-paced) patch efforts some time ago.

**Comment by adrianlopezroche** [comment]
This project should not be considered abandoned, but I'm also not in a hurry to make lots of changes. One reason is that fdupes has matured enough to suit my needs which is why I wrote the program in the first place. I think fdupes is pretty damn useful the way it is right now, and I don't want feature creep to turn it into something more complicated than it needs to be. The features I do wish to add I get no help with, so it seems no one else is in a hurry to make changes others want.

Another reason for the lack of activity is I often disagree with the kinds of features people request of me. I'm happy to share fdupes with others because I think they may find it useful, but I work on it to suit myself. I do not get paid for this, and feature requests should be viewed in such a light. I owe no one any updates, though I'm happy to accommodate people's requests when I feel they would improve the program enough to be worth the effort and can do so in a way that retains the program's simplicity.

On the subject of you "hijacking my project on my own turf," I must say I do have somewhat of a problem with your attitude. One reason I asked you to rename what was then known as fdupes-jordy is that I got the distinct impression you wanted to turn yourself into the de facto maintainer for fdupes because you weren't happy with the job I was doing (or not doing). I did incorporate a few of your patches, but some of them I didn't want to incorporate or wanted to implement differently. The hashing algorithm is the biggest example that springs to mind, but there were others as well. I also recall you being involved in an argument with another user on this board, and I didn't like the way you reacted. 

I get that you want to help, but you don't always go about it the best way. You might not, for instance, seize upon a thread about fdupes version numbers to advertise your fork of fdupes. Bringing up jdupes on this thread won't fix openSUSE's versioning problems, so your claim about this being "the only way I can help out people ... looking for assistance" seems more self-serving than helpful.

**Comment by jbruchon** [comment]
Alright, I understand your position. I'll stop communicating with your users.

**Comment by adrianlopezroche** [comment]
> Pretty much all distros have them.

I'm sure fdupes isn't the only program to present such problems. It's the kind of thing distros need to be able to deal with, even if it's not ideal. I don't want to switch back to 1.61 on my end, and I don't want to release a version 2.0.0 that's pretty much identical to 1.6.1. I'm OK with exherbo using 1.61 on its own end if that's what's required to have a consistent versioning sequence.

As for Gentoo, 1.6.1 fits right in with 1.5.1, no?

**Comment by hasufell** [comment]
> I'm sure fdupes isn't the only program to present such problems.

From 5+ years of packaging experience I'd say it's the second one.

> It's the kind of thing distros need to be able to deal with, even if it's not ideal.

You're proposing all distros implement package manager hacks in order to deal with a corner case of 0.02%, where upstream failed to release linear versions? It's an upstream bug and has to be fixed upstream.

**Comment by sandrotosi** [comment]
just as a datapoint, debian introduced epochs a couple of decades ago exactly to deal with this (rare) situations. debian has fdupes 1.6.1 no problem

**Comment by JohnAZoidberg** [comment]
Anyway there have been a few commits since 2016 and a new release would be due (whatever the version).

**Comment by albertyw** [comment]
It looks like fdupes now has a [2.0.0 release](https://github.com/adrianlopezroche/fdupes/releases/tag/2.0.0).  Ubuntu still has the old 1.6.1 version but compiling from source with the [install instructions](https://github.com/adrianlopezroche/fdupes/blob/2.0.0/INSTALL.enduser) isn't too hard.

**Comment by adrianlopezroche** [comment]
Fixed.
