### ISSUE TITLE
Feature Request -print0 option

### ISSUE THREAD

**Issue by jasonblewis** [adrianlopezroche/fdupes#82]
some command line tools take null terminated strings of file names as an input. It would be usefule if fdupes could emit the list of dupe files null terminated. For example xargs could make use of this feature. (see xargs options --null or -0)

**Comment by DEVoytas** [comment]
How would that work?
Do you want to have null-separated files in each set of matches, null-separated matching sets or null-separated everything, i.e. all current spaces and new lines replaced by `'\0'`?

**Comment by jasonblewis** [comment]
all new lines (between file names) replaced by `\0`. 
my recent use case was I dumped the output of `fdupes -f` to a file for later examining and processing. it would have been useful if the file names were terminated with `\0` for easy piping into xargs. 

I think it would add a even more versatility to fdupes

**Comment by DEVoytas** [comment]
So basically you want the same behaviour as `-1 --sameline` but instead of spaces as separator `\0` character would be used. And matching sets would still be separated by new line. Correct ?

**Comment by jasonblewis** [comment]
I think the new lines should also be replaced with a `\0`. Imagine a scenario where file names have `\n` in them, `\0` means you don't have to worry about and piping it into other tools that know about null terminated file name strings will just work

**Comment by DEVoytas** [comment]
In that case, how would you know which file belongs to which set ?
Usually you use fdupes to identify one "original" file and remove duplicates.
If you separate everything with a `\0`, you get one unified list of files and have no way of knowing which file is the same as the other.

**Comment by jasonblewis** [comment]
doesn't the -f option exclude the first one of each dupe? so no need to know which set is which if you are trying to delete the dupes but leave one original. however I see your point though for other uses. maybe the null option should only work where it makes sense that you'd be sending the entire list to some other tool?

**Comment by DEVoytas** [comment]
Right, used combined with -f option, it would indeed allow you to keep one copy of the file, but you still do not know which one ('first' is just random file that fdupes happens to find first). Most of the time users want to decide which of the files to keep, so even combined with -f usefulness is rather limited. And regarding the standalone case, there still seem to be no valid use case IMO.

**Comment by jbruchon** [comment]
`fdupes $PATH | tr '\n' '\0' | xargs -0 command`

No need to add this to `fdupes`. Use `tr`. The only names this solution won't work on is names that contain newlines. Something tells me that's not going to be a problem.

**Comment by jasonblewis** [comment]
@jbruchon the case where file names might have a `\n` in them is precisely the case that makes having a null terminated list useful. Agreed it's rare but in the even of needing to de-dupe 100,000s of files it just means the user has to do one less thing, worrying about strange file names. 

I agree this is not a common use case, but it is a use case, as I just used fdupes for precisely this problem. 480000 duplicate files due to a software issue. fdupes was very handy for that but i did have to spend some time checking filenames would be safe to pipe into xargs.

**Comment by llimeht** [comment]
> Having files with newlines in the names is a really bad idea anyway, usually only caused by bad shell scripting and programming.

Bug and security databases that are littered with cases where incorrect assumptions were made about what was legal in a filename with space and newline being the most commonly missed legal characters. Yes, the shell will split on ' ' and '\n' and failure to handle this can lead to bugs. Yes it's best to avoid such names. At the same time, malicious users seem to have the ability to come up with very creative and interesting ways of exploiting this splitting; standard tools (find, grep, xargs, tar, ...) fix these problems with null separation since null is an illegal character in a POSIX path and it would be great if fdupes could fit better into that ecosystem.

**Comment by pabs3** [comment]
I can't seem to convert this issue to a pull request, but please merge the commit I created to implement this feature:

https://github.com/pabs3/fdupes/commit/3dd14ad2ee30dd72ba3fbfc4779488b83a8e8232

**Comment by jbruchon** [comment]
What happens if `-S` gets passed? Are you going to let `xargs` eat up "3216 bytes each:" as a parameter too? If you want to implement this, you have to explain what you're expecting to be able to do with plain `xargs` that the program can't already do internally and how you're going to handle all the corner cases for the myriad options `fdupes` provides. What happens if `--sameline` gets passed? What about `--delete`? If I go `fdupes -0dN path` will the list of automatically deleted files be output with NUL termination instead of newlines? What if I want to pass a list of auto-deleted files to `xargs` to run a command that removes the paths from some sort of database?

The code offered up only affects `printmatches()` and doesn't handle the added text for the `-S` case. It also doesn't change any other sort of output mode in the same way. At a minimum there should be a check done to error out if the user specifies incompatible flags that won't behave as expected with the new option.

A far simpler solution is to (A) feed a shell script that does any arbitrary thing you want with the data and (B) don't stick newlines in your file names in the first place. In fact, if you are worried about non-specific malicious users exploiting `fdupes` newlines to trick you into messing up the wrong file on your system, add a check in the shell script that chains newlined file names together via bash arrays and tests for existence of the new names containing embedded newline(s) before taking action. It'd take less time to write than the proper C code for `fdupes` to remain consistent across the board with the new option.

**Comment by DEVoytas** [comment]
@jbruchon made many good points.
I guess the main issue with this option is that it's not as easy do define how it should really behave as it is in `find` case. This is because `find` returns set of elements (files), while `fdupes` returns set of sets, with possible extra data ('-S` option).

**Comment by jasonblewis** [comment]
This turned into something far more challenging that I imagined. I totally see why its difficult, while stilI I think it would be useful for some use cases. Thanks for everyones input and even if you don't implement this feature, it was good to hash out.
